# Generated by Django 3.0.8 on 2020-08-03 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date',
            new_name='dateCreated',
        ),
        migrations.AddField(
            model_name='note',
            name='dateEdited',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
