# Generated by Django 3.0.8 on 2020-08-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20200803_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='dateEdited',
            field=models.DateField(auto_now=True),
        ),
    ]
