# Generated by Django 3.0.8 on 2020-08-03 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_note_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='dateCreated',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
